version: '2'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8888:80
      - 8777:8000
    environment:
        WEB_DOCUMENT_ROOT: /app/public

  composer:
    build: .
    volumes:
      - .:/app
    command: composer install
    working_dir: /app
